=== No-rmand/TP_Idec_Mangatheque/MaMangatheque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mangatheque">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="auteur" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="series">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="serie" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tome" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="numero" type="xs:integer"/>
                                                                <xs:element name="dateParution" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="possede" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="Digital"/>
                                                                        <xs:enumeration value="Physique"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="langue" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="Francais"/>
                                                                        <xs:enumeration value="Anglais"/>
                                                                        <xs:enumeration value="Portugais"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="longueur" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Serie longue"/>
                                                            <xs:enumeration value="Serie courte"/>
                                                            <xs:enumeration value="One shot"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="nbTome" type="xs:integer" use="required"/>
                                                <xs:attribute name="genre" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Shonen"/>
                                                            <xs:enumeration value="Shojo"/>
                                                            <xs:enumeration value="Seinen"/>
                                                            <xs:enumeration value="Josei"/>
                                                            <xs:enumeration value="Kodomo"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="titre" type="xs:string" use="required"/> 
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>                                                                                                           
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nom" type="xs:string" use="required"/>
                    </xs:complexType>   
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== No-rmand/TP_Idec_Mangatheque/MaMangatheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--                                       
 _    _                         _   _      __                   
|  \/  |                       | | | |     \_\                  
| \  / | __ _ _ __   __ _  __ _| |_| |__   ___  __ _ _   _  ___ 
| |\/| |/ _` | '_ \ / _` |/ _` | __| '_ \ / _ \/ _` | | | |/ _ \
| |  | | (_| | | | | (_| | (_| | |_| | | |  __/ (_| | |_| |  __/
|_|  |_|\__,_|_| |_|\__, |\__,_|\__|_| |_|\___|\__, |\__,_|\___|
                     __/ |                        | |           
                    |___/                         |_|           
-->
<mangatheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MaMangatheque.xsd">
    <auteur nom="Takehiko Inoue">
        <series>
            <serie longueur="Serie longue" nbTome="31" genre="Seinen" titre="Vagabond">
                <tome possede="Digital" langue="Anglais">
                    <numero>1</numero>
                    <dateParution>24.03.2001</dateParution>
                </tome>
                <tome possede="Digital" langue="Anglais">
                    <numero>2</numero>
                    <dateParution>29.05.2001</dateParution>
                </tome>
            </serie>
            <serie longueur="Serie longue" nbTome="37" genre="Shonen" titre="Slam Dunk">
                <tome possede="Digital" langue="Anglais">
                    <numero>1</numero>
                    <dateParution>01.03.1999</dateParution>
                </tome>
                <tome possede="Digital" langue="Anglais">
                    <numero>2</numero>
                    <dateParution>01.05.1999</dateParution>
                </tome>
            </serie>
        </series>
    </auteur>
    <auteur nom="Akira Toriyama">
        <series>
            <serie longueur="Serie longue" nbTome="42" genre="Shonen" titre="Dragon Ball">
                <tome possede="Physique" langue="Francais">
                    <numero>1</numero>
                    <dateParution>24.05.1993</dateParution>
                </tome>
                <tome possede="Physique" langue="Francais">
                    <numero>2</numero>
                    <dateParution>17.06.1993</dateParution>
                </tome>
                <tome possede="Physique" langue="Francais">
                    <numero>3</numero>
                    <dateParution>22.09.1993</dateParution>
                </tome>
            </serie>
        </series>
    </auteur>
    <auteur nom="Takeshi OBATA">
        <series>
            <serie longueur="Serie longue" nbTome="20" genre="Shonen" titre="Bakuman">
                <tome possede="Digital" langue="Francais">
                    <numero>1</numero>
                    <dateParution>02.07.2010</dateParution>
                </tome>
                <tome possede="Digital" langue="Francais">
                    <numero>2</numero>
                    <dateParution>02.07.2010</dateParution>
                </tome>
                <tome possede="Digital" langue="Francais">
                    <numero>3</numero>
                    <dateParution>17.09.2010</dateParution>
                </tome>

            </serie>
        </series>
    </auteur>
</mangatheque>
